import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const C = {
  bg: "#FAF9F4", card: "#FFFFFF", ink: "#191C19",
  inkSoft: "#565B55", inkFaint: "#969B92", line: "#E8E6DC",
  gold: "#B98A2E", goldWash: "#FBF3DF",
};
const FD = "'Space Grotesk', sans-serif";
const FB = "'Hanken Grotesk', system-ui, sans-serif";

const SECTIONS = [
  {
    title: "1. What Sheetly is",
    body: `Sheetly is a bank statement analysis tool. It helps individuals understand their spending, detect hidden charges, and export their transactions to Excel. It also helps loan agents and CAs analyse a borrower's financial health from their bank statements.

Sheetly is a decision-support tool. It is not a licensed financial advisor, bank, NBFC, or credit bureau. The reports and figures generated by Sheetly are for informational purposes only.`,
  },
  {
    title: "2. Acceptance of terms",
    body: `By creating an account or using Sheetly, you agree to these Terms of Service. If you do not agree, please do not use the service.

We may update these terms from time to time. Continued use of Sheetly after an update means you accept the new terms.`,
  },
  {
    title: "3. Your account",
    body: `You are responsible for keeping your account credentials secure. You must not share your account with others or use Sheetly on behalf of another person without their permission.

You must be at least 18 years old to use Sheetly.`,
  },
  {
    title: "4. Acceptable use",
    body: `You agree to use Sheetly only for lawful purposes. You must not:
• Upload bank statements that belong to someone else without their explicit written consent
• Use Sheetly to facilitate fraud, money laundering, or any illegal activity
• Attempt to reverse-engineer, copy, or misuse our technology
• Upload malicious files or attempt to attack our systems
• Use Sheetly to make lending decisions without independent verification

For loan agents and CAs: you are responsible for obtaining proper consent from borrowers before uploading their statements.`,
  },
  {
    title: "5. Accuracy of results",
    body: `Sheetly uses AI to extract and analyse bank statement data. While we work hard to ensure accuracy, extracted data may occasionally contain errors — especially for unusual or scanned bank statement formats.

All Sheetly outputs are labelled as auto-detected and should be verified before being relied upon for any financial, lending, or legal decision. Sheetly is a screening and efficiency tool, not a guaranteed source of truth.

We are not liable for decisions made based on Sheetly's output without independent verification.`,
  },
  {
    title: "6. Payments and refunds",
    body: `Paid plans are billed monthly. You can cancel at any time and will retain access until the end of the billing period.

Per-report pricing (Business plan) is charged per report generated. These are non-refundable once a report has been generated.

For billing issues or refund requests, contact hello@sheetly.in within 7 days of the charge.`,
  },
  {
    title: "7. Data and privacy",
    body: `Your use of data on Sheetly is governed by our Privacy Policy (sheetly.in/privacy), which is incorporated into these terms by reference.

The most important point: we do not store your bank statements. PDFs are deleted immediately after processing.`,
  },
  {
    title: "8. Limitation of liability",
    body: `Sheetly is provided "as is." To the maximum extent permitted by law, we are not liable for:
• Any financial loss arising from reliance on Sheetly's output
• Errors or omissions in extracted data
• Business losses, indirect losses, or consequential damages
• Service downtime or interruptions

Our total liability to you for any claim shall not exceed the amount you paid to Sheetly in the 3 months prior to the claim.`,
  },
  {
    title: "9. Intellectual property",
    body: `Sheetly and all its content, design, and technology are owned by us. You may not copy, reproduce, or redistribute any part of Sheetly without written permission.

The bank statement data you upload remains yours. We claim no ownership over your financial data.`,
  },
  {
    title: "10. Governing law",
    body: `These terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts of Guwahati, Assam, India.`,
  },
  {
    title: "11. Contact",
    body: `For any questions about these terms: hello@sheetly.in`,
  },
];

export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh", background: C.bg, fontFamily: FB }}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=Hanken+Grotesk:wght@400;500;600;700;800&display=swap'); * { box-sizing: border-box; }`}</style>
      <Navbar />

      <div style={{ maxWidth: 720, margin: "0 auto", padding: "60px 22px 80px" }}>
        <div style={{ marginBottom: 40 }}>
          <h1 style={{ fontFamily: FD, fontWeight: 700, fontSize: 38, letterSpacing: -0.9, margin: "0 0 12px", color: C.ink }}>Terms of Service</h1>
          <div style={{ fontFamily: FB, fontSize: 13.5, color: C.inkFaint }}>Last updated: June 2025</div>
          <div style={{ marginTop: 16, background: C.goldWash, border: `1px solid ${C.gold}33`, borderRadius: 12, padding: "14px 18px" }}>
            <div style={{ fontFamily: FB, fontSize: 14.5, color: C.gold, fontWeight: 600, lineHeight: 1.55 }}>⚠️ Important: Sheetly is a decision-support tool, not a licensed financial advisor. All reports are for informational purposes and should be independently verified before being used for any lending or financial decision.</div>
          </div>
        </div>

        {SECTIONS.map((s, i) => (
          <div key={i} style={{ marginBottom: 36 }}>
            <h2 style={{ fontFamily: FD, fontWeight: 600, fontSize: 18, color: C.ink, marginBottom: 10 }}>{s.title}</h2>
            <div style={{ fontFamily: FB, fontSize: 14.5, color: C.inkSoft, lineHeight: 1.75, whiteSpace: "pre-line" }}>{s.body}</div>
          </div>
        ))}
      </div>

      <Footer />
    </div>
  );
}